### PR TITLE
Migrate spray to akka http

### PR DESCRIPTION
**Pull request by pepegar**
[Spray](http://spray.io) is not mantained anymore, and they are migrating it to `akka-http`.  The purpose of this Pull Request is to make it possible to use `spray-aws` when you're using `akka-http`.
### Caveats of the migration

`spray-client` apis are not migrated to Akka, and I decided to use the `akka-streaming` way of implementing HTTP clients. This added another property to every `*Props` object, the [`ActorMaterializer`](http://doc.akka.io/japi/akka-stream-and-http-experimental/2.0/akka/stream/ActorMaterializer.html).

However, the only thing needed to make this work is to add an `implicit val` for your `ActorMaterializer` and you're ready to go.

### CODE REVIEW

**Comment by pepegar** [comment]
@sclasen ready for review, please provide any feedback! :)

**Comment by sclasen** [comment]
looks good to me, shall I publish a snapshot to oss.sonatype.org?

**Comment by pepegar** [comment]
Sounds good!

**Comment by sclasen** [comment]
@pepegar forgot this new repo would require a JIRA ticket at sonatype, so it will be a day or 2 before I can push a release probably.

**Comment by pepegar** [comment]
Ok, no probs! I'm sure we can wait for it!

**Comment by ghost** [comment]
@pepegar Wow, this is awesome! Great work :+1:

**Comment by sclasen** [comment]
Gah, so I guess it wasnt a Sonatype ticket to publish this. In the translation from Build.scala to build.sbt  somehow the subprojects are not getting the 'organization' set properly.

Will try and figure out the build.sbt wizardry....

**Comment by sclasen** [comment]
@pepegar @petter-fidesmo published to oss.sonatype snapshot repo!

**Comment by pepegar** [comment]
Auch... really?  I'll try to take a look at that!

**Comment by sclasen** [comment]
Got it fixed up already here https://github.com/sclasen/akka-aws/commit/bf1e36790d7ff976fed5d332fee4b1a90aef5c4a

lmk if it looks/works as expected and I can cut a non-snapshot to maven central

**Comment by pepegar** [comment]
Trying it out, will update you ASAP!

**Pull request merged**
